### ISSUE TITLE
Invalid thrift fact records should not kill entire ingest process

### ISSUE THREAD

**Issue by blever** [ambiata/ivory#585]
Unlike text-based fact ingestion, when ingesting thrift-based facts, if a fact value is invalid it will kill the entire ingest process. Rather, the text-based fact ingestion will write invalid facts `/errors`.

The scenario that is cropping up a lot are `date` fact values. Ivory will validate date values on ingest but the thrift values are just strings.

**Comment by markhibberd** [comment]
To be clear the expected behaviour is:
 - Valid thrift, invalid value, should get error bucketed.
 - Invalid thrift, i.e. the bytes can't even be deserialized, should be a hard error.

This should address the date issue, but not have bad bytes in the retry buckets, and prevent accidental total failure if someone has the wrong thrift definitions.

**Comment by blever** [comment]
:+1:

**Comment by markhibberd** [comment]
@charleso And can you look at this one as well. They should both be small (I think).
